title: Vonge

plugins:
  - jekyll-bookshop
  - jekyll-sitemap
  - jekyll/tagging

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ./component-library

exclude:
  - postcss.config.js
  - node_modules

# include:
#   - _cloudcannon

# First casousel is the hero background
carousels:
  - images: 
    - image: ./images/project-6.jpg
    - image: ./images/project-7.jpg
    - image: ./images/project-8.jpg
    - image: ./images/project-9.jpg
  # - images: 
  #   - image: /uploads/slider/image5.jpg
  #   - image: /uploads/slider/image6.jpg
  #   - image: /uploads/slider/image7.jpg
  #   - image: /uploads/slider/image8.jpg

collections_dir: 'collections'

collections:
  pages:
    output: true
    permalink: /:title/
  projects:
    output: true
    permalink: /project/:slug
  testimonials:
    output: true
  posts:
    output: false
    permalink: /blog/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: /
  - scope:
      type: projects
    values:
      layout: project
  - scope:
      type: posts
    values:
      layout: post

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title
