# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero Image
  description: Hero image
  icon: wysiwyg
  tags:
    - Headers

# Defines the structure of this component, as well as the default values
blueprint:
  title:
  text:
  carousel:
    - image: ""
    - image: ""
    - image: ""
    - image: ""
  duration: 2

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: "Si-studio"
  text: "Your dream come true"
  carousel:
      - image: /images/project-6.jpg
      - image: /images/project-7.jpg
      - image: /images/project-8.jpg
      - image: /images/project-9.jpg
  duration: 2

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
